name: rancor-v3

services:
    migrate:
        build:
            context: .
            dockerfile: migrate.Dockerfile

    app:
        build: .
        container_name: RANCOR
        restart: unless-stopped

        environment:
            NODE_ENV: production

        env_file:
            - .env

        depends_on:
            - migrate

networks:
    proxy:
        external: true
